// Generated by https://quicktype.io

export interface User {
  confirmed: boolean;
  blocked: boolean;
  rank: number;
  _id: string;
  username: string;
  email: string;
  provider: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
  role: Role;
  mem: string;
  updated_by: string;
  avatar: Avatar;
  id: string;
  mems: Mem[];
}

export interface Avatar {
  _id: string;
  name: string;
  alternativeText: null;
  caption: null;
  hash: string;
  ext: string;
  mime: string;
  size: number;
  width: number;
  height: number;
  url: string;
  formats: Formats;
  provider: string;
  related: string[];
  createdAt: string;
  updatedAt: string;
  __v: number;
  id: string;
}

export interface Formats {
  thumbnail: Thumbnail;
}

export interface Thumbnail {
  name: string;
  hash: string;
  ext: string;
  mime: string;
  width: number;
  height: number;
  size: number;
  path: null;
  url: string;
}

export interface Mem {
  likes: number;
  dislikes: number;
  isPublic: boolean;
  isReported: boolean;
  categories: string[];
  _id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
  image: Avatar;
  user: User;
  id: string;
}

export interface Role {
  _id: string;
  name: string;
  description: string;
  type: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
  id: string;
}
